### ISSUE TITLE
get error by running program

### ISSUE THREAD

**Issue by wentaoxandry** [georgesterpu/Sigmedia-AVSR#3]

**Comment by georgesterpu** [comment]
Hello @wentaoxandry 

I am not sure if you managed to fix the problem, but it is certainly a bug on my side.
 
It occurs when constructing the initial state for a bimodal decoder, likely because I changed the format of the `encoding_units_per_layer` parameter from  a tuple of ints to a tuple of tuples of ints (one for each modality) and pushed the update without running tests on this class that I rarely use.

Please feel free to submit a fix, I will also do it very soon.

**Comment by wentaoxandry** [comment]
Hallo @georgesterpu 

Thank you for your answer, I will try my best to figure it out, but I'm new with tensorflow, I don't know if I can finish it. Please tell me if you finish this bug.

**Comment by georgesterpu** [comment]
@wentaoxandry Please pull and have another try now.
