### ISSUE TITLE
how to pad features and labels to same length in one batch ?

### ISSUE THREAD

**Issue by kobenaxie** [georgesterpu/Sigmedia-AVSR#7]
Hi, I can not find the code for padding, could you point out please ?
And what is the meaning of [`MASK`, `END`] in unit dict, where used it

**Comment by wentaoxandry** [comment]
Hi, I also want ask the same question. By the way, I don't find code split sentence into characters, what is the start mark and what is the end mark. The space between the words will be represent by 'GO'?

Thank you

**Comment by georgesterpu** [comment]
We rely on the `tf.data.Dataset.padded_batch` method to do the paddings.

`padded_batch` is used [here](https://github.com/georgesterpu/Sigmedia-AVSR/blob/master/avsr/io_utils.py#L106), in the function that creates the `Dataset` and the `Iterator`

`MASK` and `END` are special tokens that I occasionally found in the predicted ids.
I cannot remember exactly why they appeared there, but my best guess is the beam search decoder. We kept them in the unit dictionary just for convenience, so that the reverse lookup to graphemes would be error free. In any case, these symbols are removed [here](https://github.com/georgesterpu/Sigmedia-AVSR/blob/master/avsr/utils.py#L45) before the prediction is written to a file.
